export const technologies = {
    react: 'React',
    js: 'JavaScript',
    html5: 'HTML',
    css3: 'CSS',
    materialui: 'Material UI',
    bootstrap5: 'Bootstrap 5',
    mongodb: 'MongoDB',
    mongoose: 'Mongoose',
    mysql: 'MySQL',
    nodejs: 'Node.js',
    expressjs: 'Express',
    redux: 'Redux',
    reactrouter: 'React Router',
    firebase: 'Firebase',
    jest: 'Jest',
    reacttestinglibrary: 'React Testing Library',
    git: 'Git',
    github: 'GitHub',
    postman: 'Postman',
    jira: 'Jira',
    jenkins: 'Jenkins',
};
